feat: add more info at subcommand example
HAECHI-LABS/henesis-cli pull request #45
Opened 2019-06-08 07:29 UTC by cloudinertia

#44

2019-06-10 01:09 UTC, Nipol approved these changes

2019-06-14 05:07 UTC, JhChoy requested changes

2019-06-14 05:07 UTC, JhChoy commented on src/commands/integration/describe.ts
> +  public static examples = [`$ henesis integration:describe  my-integration-id-xqxz`];
2 space => 1 space

2019-06-14 10:30 UTC, cloudinertia commented on src/commands/integration/describe.ts
> +  public static examples = [`$ henesis integration:describe  my-integration-id-xqxz`];
fixed!

2019-06-14 10:31 UTC, JhChoy approved these changes

2019-06-14 10:33 UTC, merged